name: Tester

on:
  push:
    branches:
      - "master"
  pull_request:

permissions:
  contents: read

env:
  default_node_version: "lts/*"

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}

      - name: Install Dependencies
        run: npm i

      - name: ESLint
        run: |
          npm run eslint

  tester:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ '18','20','22' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm i

      - name: Test
        run: |
          npm run test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}

      - name: Install Dependencies
        run: npm install

      - name: Coverage
        run: npm run test-cov

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}